spring:
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:@liquid_nacos.addr@}

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      metrics:
        enabled: true

      # TODO: use nacos dynamic configuration

      globalcors:
        corsConfigurations:
          '[/**]':
#            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE


#      filter:
#        remove-hop-by-hop:
#          headers:
#            - trailer
#            - te
#            - keep-alive
#            - transfer-encoding
#            - upgrade
#            - proxy-authenticate
#            - connection
#            - proxy-authorization
#            - x-application-context
#            - access-control-allow-credentials
#            - access-control-allow-headers
#            - access-control-allow-methods
#            - access-control-allow-origin
#            - access-control-max-age
#            - vary

      routes:
        - id: liquid-media
          uri: lb://liquid-media
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix=1

        - id: liquid-core
          uri: lb://liquid-core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1

        - id: liquid-auth
          uri: lb://liquid-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: liquid-git
          uri: lb://liquid-git
          predicates:
            - Path=/git/**
          filters:
            - StripPrefix=1
