#build:
#  version: @project.version@
#
#spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false
#  servlet:
#    multipart:
#      max-file-size: 200MB
#      max-request-size: 200MB
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: UTC
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#logging:
#  file:
#    path: logs
#    name: liquid-media.log
#
#snowflake:
#  datacenter-id: 1
#  machine-id: 1

server:
  port: 8004

spring:
  application:
    name: spring-cloud-alibaba-oauth2-gateway
  cloud:
    gateway: # config the routes for gateway
      discovery:
        locator:
          enabled: true
      routes:
        - id: spring-cloud-alibaba-gateway     #将/provider1/开头的请求转发到provider1
          uri: lb://liquid-media
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1               #表明前缀/provider1需要截取掉
    nacos:
      discovery:
        server-addr=127.0.0.1:8848
      locator:
        enable: true
        lower-case-service-id: true

    loadbalancer:
      ribbon:
        enabled: F
