spring:
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:@liquid_nacos.addr@}

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      metrics:
        enabled: true

      # TODO: use nacos dynamic configuration
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowed-origin-patterns: "*"
            allowedMethods: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
            maxAge: 360000



      #      filter:
      #        remove-hop-by-hop:
      #          headers:
      #            - trailer
      #            - te
      #            - keep-alive
      #            - transfer-encoding
      #            - upgrade
      #            - proxy-authenticate
      #            - connection
      #            - proxy-authorization
      #            - x-application-context
      #            - access-control-allow-credentials
      #            - access-control-allow-headers
      #            - access-control-allow-methods
      #            - access-control-allow-origin
      #            - access-control-max-age
      #            - vary

      routes:
        - id: liquid-media
          uri: lb://liquid-media
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix=1

        - id: liquid-core
          uri: lb://liquid-core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1

        - id: liquid-auth
          uri: lb://liquid-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: liquid-git
          uri: lb://liquid-git
          predicates:
            - Path=/git/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Headers Access-Control-Allow-Credentials,RETAIN_UNIQUE
