spring:
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:@liquid_nacos.addr@}

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      metrics:
        enabled: true

      # TODO: use nacos dynamic configuration
      routes:
        - id: liquid-media
          uri: lb://liquid-media
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix=1
        - id: liquid-core
          uri: lb://liquid-core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
