spring:
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:@liquid_nacos.addr@}

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      metrics:
        enabled: true

      # TODO: use nacos dynamic configuration
      routes:
        - id: liquid-media
          uri: lb://liquid-media
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix=1
        - id: liquid-core
          uri: lb://liquid-core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1

jwt:
  encrypt-secret: 'cQfTjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8y/A?D(G+KbPeShVmYq3t6w9z$C&E)'
  default-expire-time: 86400000
  remember-expire-time: 2678400000