build:
  version: @project.version@

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    path: classpath:logs
    name: liquid-git.log

storage:
  git: storage/git
  git-tmp: storage/git-tmp
  git-bkp: storage/git-bkp
