document:
  - '**/*.md'
  - '**/*.rst'

ci:
  - '.github/**/*'

deploy:
  - 'liquid-docker/**/*'
  - '**/Dockerfile'
  - '**/*compose.yml'

cloud-base:
  - 'liquid-gateway/**/*'
  - 'liquid-docker/image/**/*'

core:
  - 'liquid-core/**/*'

media:
  - 'liquid-media/**/*'
