document:
  - '**/*.md'
  - '**/*.rst'

ci:
  - '.github/**/*'

deploy:
  - '**/Dockerfile'
  - '**/*compose.yml'

micro-services:
  - 'liquid-eureka/**/*'

service:
  - 'liquid-service/**/*'

media-server:
  - 'liquid-media/**/*'
