build:
  version: @project.version@

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  redis:
    host: localhost
    port: 16380
    database: 0
    password:
    timeout: 1200
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    path: classpath:logs
    name: liquid-media.log

jwt:
  encrypt-secret: 'cQfTjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8y/A?D(G+KbPeShVmYq3t6w9z$C&E)'
  default-expire-time: 86400000
  remember-expire-time: 2678400000


aliyun:
  sms:
    access-key-id: "LTAI5tDCCZgDT7ounNJN1exq"
    access-key-secret: "IBypcl8baB7201PI4V6zpK5wgRyeJz"
    sign-name: "liquid"
    templates:
      key1:
        template-code: "SMS_264935151"


