spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @spring.profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
  messages:
    basename: static.i18n.message
    cache-duration: 3600
    encoding: UTF-8

server:
  port: @liquid_service.port@
  servlet:
    context-path: /api
