build:
  version: @project.version@

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    path: logs
    name: liquid-media.log

snowflake:
  datacenter-id: 1
  machine-id: 1
