build:
  version: @project.version@

server:
  port: @liquid_media.port@
  servlet:
    context-path: /media

spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @spring.profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  messages:
    basename: static.i18n.message
    cache-duration: 3600
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  file:
    path: logs
    name: liquid-media.log

snowflake:
  datacenter-id: 1
  machine-id: 1

minio:
  endpoint: http://localhost:@liquid_media.minio@
  root-user: liquid
  root-password: liquid_MS_minio
  timeout: 10000

eureka:
  client:
    allow-redirects: true
    service-url:
      defaultZone: http://localhost:@liquid_eureka.port@/eureka
