name: Build & Tests

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.pull_request.head.ref }} from ${{ github.event.pull_request.head.repo.full_name }}
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Spotless check
        run: mvn spotless:check

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
