name: Build & Tests

on:
  push:
    branches: [ master, main ]
  pull_request_target:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR #${{ github.event.number }}
        if: github.event_name == 'pull_request_target'
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.number }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Spotless check
        run: mvn spotless:check

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
