name: Checkstyle

on:
  pull_request_target:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: pr_number
        if: github.event_name == 'pull_request_target'
        uses: 8BitJonny/gh-get-current-pr@2.1.2

      - name: Checkout PR \#${{ steps.pr_number.outputs.number }}
        if: github.event_name == 'pull_request_target'
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ steps.pr_number.outputs.number }}

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          checkstyle_config: 'checkstyle.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: diff_context
          reporter: 'github-pr-review'
