name: Checkstyle

on:
  pull_request_target:

jobs:
  intellij:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Jetbrains style
        uses: findologic/intellij-format-action@v1
        with:
          include-glob: '*.kt,*.java'
          path: .

      - name: Commit formatted files
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: EndBug/add-and-commit@v8.0.2
        with:
          default_author: github_actor
          message: "style: format java code (intellij)"

  main:
    name: Checkstyle
    runs-on: ubuntu-latest
    needs: intellij

    steps:
      - name: Checkout pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          checkstyle_config: 'checkstyle.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: diff_context
          reporter: 'github-pr-review'
