name: Checkstyle

on:
  pull_request_target:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.pull_request.head.ref }} from ${{ github.event.pull_request.head.repo.full_name }}
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          checkstyle_config: 'checkstyle.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: diff_context
          reporter: 'github-pr-review'
